<a href="https://colab.research.google.com/github/Shantanu070521/DeepLearninglab/blob/main/practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#vector addition

In [4]:
#define
vec_a=np.array([1,2,3])
vec_b=np.array([4,5,6])

In [6]:
#perform element wise additon
vec_c=vec_a+vec_b
print("---Vector Addition---")
print("Vector a:",vec_a)
print("Vector b:",vec_b)
print("Vector c:",vec_c)

---Vector Addition---
Vector a: [1 2 3]
Vector b: [4 5 6]
Vector c: [5 7 9]


In [8]:
#matrix multiplication
matrix_x=np.array([[1,2,3],[4,5,6]])
matrix_y=np.array([[5,6],[7,8],[2,3]])
matrix_product=np.dot(matrix_x,matrix_y)
print("---Matrix Multiplication---")
print("Matrix x:\n",matrix_x)
print("Matrix y:\n",matrix_y)
print("Matrix product:\n",matrix_product)

---Matrix Multiplication---
Matrix x:
 [[1 2 3]
 [4 5 6]]
Matrix y:
 [[5 6]
 [7 8]
 [2 3]]
Matrix product:
 [[25 31]
 [67 82]]
